set-option -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'rose-pine/tmux'

set-option -g status-position top
set-option -g renumber-windows on
set-option -g detach-on-destroy off

# window と pane を 1 から始める
set-option -g base-index 1
set-window-option -g pane-base-index 1

# Prefix-c Prefix-" Prefix-% でカレントディレクトリを使う
bind-key c new-window -c "#{pane_current_path}"
bind-key '"' split-window -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"

# copy-mode に入るときのキーバインドを vi のようにする有名な設定
# https://eiji.page/blog/tmux-conf-copy-mode/
# これとは別に、copy-mode の中での挙動は `tmux show -g mode-keys` で確認できる
unbind-key -T copy-mode-vi Space
unbind-key -T copy-mode-vi Enter
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# https://github.com/rose-pine/tmux
set-option -g @rose_pine_variant "main"
set-option -g @rose_pine_status_left_append_section " "
set-option -g @rose_pine_date_time "%H:%M"
set-option -g @rose_pine_directory "on"
set-option -g @rose_pine_disable_active_window_menu "on"

bind-key -n C-s run-shell "$HOME/.zsh/bin/choose-session"
bind-key -n C-g run-shell "$HOME/.zsh/bin/choose-git"

# 実行中のプロセスがzshなら確認なしで閉じる
# https://man.openbsd.org/tmux.1#FORMATS
bind-key x if-shell "[ \"$(tmux display-message -p '#{pane_current_command}')\" = \"zsh\" ]" \
  "kill-pane" \
  "confirm-before -p 'kill-pane #{pane_title}? (y/n)' kill-pane"

# https://formulae.brew.sh/formula/tpm
run-shell "$HOMEBREW_PREFIX/opt/tpm/share/tpm/tpm"

